{{- if and .Values.secret .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- range $key, $value := .Values.secret.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
type: {{ .Values.secret.type | default "Opaque" }}
stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
---
{{- end }}