apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
  - default:
      cpu: 2000m      
      memory: 4Gi
    defaultRequest:
      cpu: 1000m
      memory: 2Gi
    type: Container